# Generated by Django 4.0.3 on 2022-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Book Name')),
                ('pub_date', models.DateField(null=True, verbose_name='Release Time')),
                ('readcount', models.IntegerField(default=0, verbose_name='Reading Volume')),
                ('commentcount', models.IntegerField(default=0, verbose_name='Comment Volume')),
                ('id_delete', models.BooleanField(default=False, verbose_name='Logical Deletion')),
            ],
            options={
                'verbose_name': 'book',
                'db_table': 'bookinfo',
            },
        ),
    ]
